secret_key_base: # rails secret

sentry:
  dsn: # From Sentry.io

devise:
  mailer_sender: noreply@better-base-api-app.com
  jwt_secret_key: # rails secret

sidekiq:
  redis_url: redis://localhost:6379/0
